import type { BlockLook } from "../catalog.ts";
import type { SiteStyleRule } from "../site-style.ts";

const specLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "56px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1)" } },
  { block: "products", part: "head", declarations: { "border-top": "1px solid var(--site-line)", "padding-top": "12px" } },
  { block: "products", part: "grid", declarations: { gap: "20px" } },
  { block: "industries", part: "list", declarations: { "padding-block": "24px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "24px" } },
  { block: "services", part: "steps", declarations: { gap: "12px" } },
  { block: "services", part: "item", declarations: { "padding-block": "16px" } },
  { block: "certifications", part: "head", declarations: { "padding-top": "16px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "12px" } },
  { block: "contact", part: "copy", declarations: { "padding-block": "20px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "24px" } },
];

const catalogLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "72px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1-display)" } },
  { block: "products", declarations: { "background-color": "var(--site-tint)", "padding-block": "24px" } },
  { block: "products", part: "grid", declarations: { gap: "24px", "padding-block": "8px" } },
  { block: "industries", part: "list", declarations: { "padding-block": "28px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "28px" } },
  { block: "services", part: "steps", declarations: { gap: "16px" } },
  { block: "services", part: "item", declarations: { "padding-block": "20px" } },
  { block: "certifications", part: "badges", declarations: { gap: "16px", "padding-block": "12px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "16px" } },
  { block: "contact", part: "copy", declarations: { "padding-block": "28px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "28px" } },
];

const capabilityLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "88px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1-display)" } },
  { block: "products", part: "head", declarations: { "padding-block": "28px" } },
  { block: "products", part: "grid", declarations: { gap: "28px" } },
  { block: "industries", part: "list", declarations: { "background-color": "var(--site-accent-soft)", "padding-block": "32px" } },
  { block: "capabilities", part: "list", declarations: { "background-color": "var(--site-accent-soft)", "padding-block": "32px" } },
  { block: "services", part: "steps", declarations: { "background-color": "var(--site-accent-soft)", gap: "20px", "padding-block": "16px" } },
  { block: "services", part: "item", declarations: { "padding-block": "24px", "padding-inline": "20px" } },
  { block: "certifications", part: "head", declarations: { "padding-top": "24px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "16px" } },
  { block: "contact", part: "copy", declarations: { "background-color": "var(--site-tint)", "padding-block": "28px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "28px" } },
];

export const brightLook: BlockLook = {
  id: "industrial",
  templateId: "forge",
  documentTitle: "明亮产品首页",
  tokens: {
    "--site-container": "1180px",
    "--site-gutter": "48px",
    "--site-gutter-narrow": "32px",
    "--site-section-space": "84px",
    "--site-section-space-narrow": "56px",
    "--site-h1": "clamp(30px, 3vw, 38px)",
    "--site-h1-display": "clamp(30px, 3vw, 38px)",
    "--site-h2": "clamp(30px, 3.6vw, 48px)",
    "--site-h1-leading": "1.04",
    "--site-h1-tracking": "-0.05em",
    "--site-heading-wrap": "anywhere",
    "--site-heading-break": "normal",
    "--site-heading-max": "100%",
    "--site-heading-text-wrap": "wrap",
    "--site-heading-tracking": "-0.045em",
    "--site-card-radius": "20px",
    "--site-media-radius": "24px",
    "--site-panel-radius": "28px",
    "--site-tile-radius": "12px",
    "--site-control-radius": "999px",
    "--site-primary-bg": "var(--site-accent)",
    "--site-primary-hover": "var(--site-accent-strong)",
    "--site-plate-bg": "var(--site-tint)",
    "--site-plate-ink": "var(--site-accent-text)",
    "--site-plate-copy": "var(--site-ink)",
    "--site-plate-muted": "var(--site-muted)",
    "--site-plate-border": "var(--site-line)",
    "--site-specs-top": "none",
    "--site-spec-gap": "12px",
    "--site-spec-cell-bg": "var(--site-tint)",
    "--site-key-bg": "var(--site-tint)",
    "--site-key-gap": "8px",
    "--site-key-divider": "none",
    "--site-footer-bg": "var(--site-bg)",
    "--site-footer-ink": "var(--site-muted)",
    "--site-footer-head": "var(--site-ink)",
    "--site-footer-top": "var(--site-rule)",
    "--site-eyebrow": "var(--site-accent-strong)",
    "--site-hero-bg": "var(--site-surface)",
    "--site-frame-pad": "0",
    "--site-frame-bg": "transparent",
    "--site-frame-border": "none",
    "--site-eyebrow-bg": "transparent",
    "--site-eyebrow-pad": "0",
    "--site-head-rule": "none",
    "--site-index-top": "none",
    "--site-index-row": "1px solid var(--site-line)",
    "--site-head-pad": "0",
    "--site-value-ink": "var(--site-ink)",
    "--site-keys-border": "var(--site-rule)",
    "--site-card-edge": "none",
    "--site-badge-edge": "none",
    "--site-panel-edge": "none",
    "--site-step-top": "none",
    "--site-list-marker": "0",
    "--site-catalog-row": "1fr",
    "--site-spec-table-border": "var(--site-rule)",
    "--site-spec-table-head": "transparent",
    "--site-panel-bg": "var(--site-tint)",
    "--site-panel-copy-bg": "transparent",
    "--site-form-card": "var(--site-surface)",
    "--site-group-columns": "1fr",
  },
  layout: {
    top: ["nav"],
    main: ["hero", "products", "commercialTerms", "equipment", "qualityProcess", "history", "industries", "capabilities", "services", "certifications", "faq", "contact"],
    bottom: ["footer"],
  },
  defaults: {
    nav: "bar",
    hero: "split",
    products: "cards",
    commercialTerms: "rows",
    equipment: "rows",
    qualityProcess: "rows",
    history: "rows",
    industries: "cards",
    capabilities: "cards",
    services: "cards",
    certifications: "badges",
    faq: "open",
    contact: "panel",
    footer: "columns",
  },
  styleDirections: {
    "spec-led": { label: "规格为主", summary: "紧凑、浅色参数格和细线分区。", rules: specLedRules },
    "catalog-led": { label: "目录为主", summary: "浅色产品带、白底描边卡片和更舒展的目录节奏。", rules: catalogLedRules },
    "capability-led": { label: "工厂实力", summary: "首屏更高，能力与流程使用浅色面板带。", rules: capabilityLedRules },
  },
};
