import type { BlockLook } from "../catalog.ts";
import type { SiteStyleRule } from "../site-style.ts";

const specLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "48px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1)" } },
  { block: "products", part: "grid", declarations: { gap: "16px" } },
  { block: "industries", part: "list", declarations: { "padding-block": "20px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "20px" } },
  { block: "services", part: "steps", declarations: { gap: "10px" } },
  { block: "services", part: "item", declarations: { "padding-block": "16px" } },
  { block: "certifications", part: "head", declarations: { "padding-top": "12px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "8px" } },
  { block: "contact", part: "copy", declarations: { "padding-block": "20px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "20px" } },
];
const catalogLedRules: SiteStyleRule[] = [
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1-display)" } },
  { block: "products", declarations: { "background-color": "var(--site-surface)", "padding-block": "20px" } },
  { block: "products", part: "grid", declarations: { gap: "12px" } },
  { block: "industries", part: "list", declarations: { "padding-block": "24px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "24px" } },
  { block: "services", part: "steps", declarations: { gap: "12px" } },
  { block: "services", part: "item", declarations: { "padding-block": "18px" } },
  { block: "certifications", part: "badges", declarations: { gap: "12px", "padding-block": "8px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "10px" } },
  { block: "contact", part: "copy", declarations: { "padding-block": "24px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "24px" } },
];
const capabilityLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "84px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1)" } },
  { block: "products", part: "head", declarations: { "padding-block": "24px" } },
  { block: "products", part: "grid", declarations: { gap: "20px" } },
  { block: "industries", part: "list", declarations: { "background-color": "var(--site-accent-soft)", "padding-block": "28px" } },
  { block: "capabilities", part: "list", declarations: { "background-color": "var(--site-accent-soft)", "padding-block": "28px" } },
  { block: "services", part: "steps", declarations: { "background-color": "var(--site-accent-soft)", gap: "16px" } },
  { block: "services", part: "item", declarations: { "padding-block": "22px", "padding-inline": "18px" } },
  { block: "certifications", part: "head", declarations: { "padding-top": "20px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "14px" } },
  { block: "contact", part: "copy", declarations: { "background-color": "var(--site-tint)", "padding-block": "26px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "26px" } },
];

export const catalogLook: BlockLook = {
  id: "export-catalog",
  templateId: "landwind",
  documentTitle: "蓝白目录首页",
  tokens: {
    "--site-container": "1180px",
    "--site-gutter": "48px",
    "--site-gutter-narrow": "32px",
    "--site-section-space": "76px",
    "--site-section-space-narrow": "52px",
    "--site-h1": "clamp(34px, 4.6vw, 58px)",
    "--site-h1-display": "clamp(34px, 4.6vw, 58px)",
    "--site-h2": "clamp(28px, 3.2vw, 40px)",
    "--site-h1-leading": "1.08",
    "--site-h1-tracking": "-0.035em",
    "--site-heading-wrap": "anywhere",
    "--site-heading-break": "keep-all",
    "--site-heading-max": "16em",
    "--site-heading-text-wrap": "balance",
    "--site-heading-tracking": "-0.03em",
    "--site-card-radius": "var(--site-radius)",
    "--site-media-radius": "calc(var(--site-radius) - 6px)",
    "--site-panel-radius": "var(--site-radius)",
    "--site-tile-radius": "0",
    "--site-control-radius": "8px",
    "--site-primary-bg": "var(--site-accent)",
    "--site-primary-hover": "var(--site-accent-strong)",
    "--site-plate-bg": "var(--site-surface)",
    "--site-plate-ink": "var(--site-accent-text)",
    "--site-plate-copy": "var(--site-ink)",
    "--site-plate-muted": "var(--site-muted)",
    "--site-plate-border": "none",
    "--site-specs-top": "3px solid var(--site-accent)",
    "--site-spec-gap": "0",
    "--site-spec-cell-bg": "var(--site-surface)",
    "--site-key-bg": "transparent",
    "--site-key-gap": "0",
    "--site-key-divider": "var(--site-rule)",
    "--site-footer-bg": "var(--site-tint)",
    "--site-footer-ink": "var(--site-muted)",
    "--site-footer-head": "var(--site-ink)",
    "--site-footer-top": "3px solid var(--site-accent)",
    "--site-eyebrow": "var(--site-accent-strong)",
    "--site-hero-bg": "linear-gradient(180deg, var(--site-tint), var(--site-bg))",
    "--site-frame-pad": "10px",
    "--site-frame-bg": "var(--site-surface)",
    "--site-frame-border": "1px solid var(--site-line)",
    "--site-eyebrow-bg": "var(--site-accent-soft)",
    "--site-eyebrow-pad": "5px 10px",
    "--site-head-rule": "2px solid var(--site-accent)",
    "--site-head-pad": "18px",
    "--site-index-top": "none",
    "--site-value-ink": "var(--site-accent-strong)",
    "--site-keys-border": "1px solid var(--site-line)",
    "--site-card-edge": "4px solid var(--site-accent)",
    "--site-badge-edge": "4px solid var(--site-accent)",
    "--site-panel-edge": "6px solid var(--site-accent)",
    "--site-step-top": "3px solid var(--site-accent)",
    "--site-list-marker": "9px",
    "--site-catalog-row": "1fr",
    "--site-spec-table-border": "1px solid var(--site-line)",
    "--site-spec-table-head": "var(--site-tint)",
    "--site-panel-bg": "var(--site-surface)",
    "--site-panel-copy-bg": "var(--site-tint)",
    "--site-form-card": "transparent",
    "--site-group-columns": "1fr",
    "--site-rule": "1px solid var(--site-line)",
    "--site-rule-strong": "2px solid var(--site-accent)",
  },
  layout: { top: ["nav"], main: ["hero", "products", "commercialTerms", "equipment", ["industries", "capabilities"], "services", "certifications", "faq", "contact"], bottom: ["footer"] },
  defaults: { nav: "bar", hero: "split", products: "rows", commercialTerms: "rows", equipment: "rows", industries: "list", capabilities: "list", services: "cards", certifications: "badges", faq: "open", contact: "panel", footer: "columns" },
  styleDirections: {
    "spec-led": { label: "规格为主", summary: "更紧凑的参数目录和分线节奏。", rules: specLedRules },
    "catalog-led": { label: "目录为主", summary: "收紧目录行距，突出产品索引。", rules: catalogLedRules },
    "capability-led": { label: "工厂实力", summary: "浅蓝能力带和更舒展的步骤卡。", rules: capabilityLedRules },
  },
};
