import type { BlockLook } from "../catalog.ts";
import type { SiteStyleRule } from "../site-style.ts";

const specLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "48px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1)" } },
  { block: "products", part: "head", declarations: { "border-top": "2px solid var(--site-ink)", "padding-top": "12px" } },
  { block: "products", part: "grid", declarations: { gap: "24px" } },
  { block: "industries", part: "list", declarations: { "padding-block": "20px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "20px" } },
  { block: "services", part: "steps", declarations: { gap: "8px" } },
  { block: "services", part: "item", declarations: { "padding-block": "14px" } },
  { block: "certifications", part: "head", declarations: { "padding-top": "16px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "8px" } },
  { block: "faq", part: "item", declarations: { "padding-block": "8px" } },
  { block: "contact", part: "copy", declarations: { "padding-top": "12px" } },
];

const catalogLedRules: SiteStyleRule[] = [
  { block: "hero", part: "specs", declarations: { "background-color": "var(--site-ink)", color: "var(--site-surface)", "border-top": "3px solid var(--site-accent)" } },
  { block: "hero", part: "spec-label", declarations: { color: "var(--site-surface)" } },
  { block: "hero", part: "spec-value", declarations: { color: "var(--site-surface)", "font-size": "28px" } },
  { block: "hero", part: "spec-value", media: "phone", declarations: { "font-size": "18px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1-display)" } },
  { block: "products", declarations: { "background-color": "var(--site-surface)", "padding-block": "24px" } },
  { block: "products", part: "grid", declarations: { gap: "24px", border: "1px solid var(--site-line)", "border-radius": "4px", "padding-block": "8px" } },
  { block: "products", part: "title", declarations: { "font-size": "var(--site-h2)" } },
  { block: "industries", part: "list", declarations: { "padding-block": "28px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "28px" } },
  { block: "services", part: "steps", declarations: { gap: "16px" } },
  { block: "services", part: "item", declarations: { "border": "1px solid var(--site-line)", "border-radius": "4px", "padding-block": "20px" } },
  { block: "certifications", part: "badges", declarations: { gap: "16px", "padding-block": "12px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "12px" } },
  { block: "contact", part: "form", declarations: { "border-radius": "4px", "padding-block": "24px" } },
];

const capabilityLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "88px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1)", "text-wrap": "pretty" } },
  { block: "hero", part: "title", media: "phone", declarations: { "font-size": "30px", "text-wrap": "pretty" } },
  { block: "products", part: "head", declarations: { "padding-block": "28px" } },
  { block: "products", part: "grid", declarations: { gap: "32px" } },
  { block: "industries", part: "list", declarations: { "background-color": "var(--site-accent-soft)", "padding-block": "32px" } },
  { block: "capabilities", part: "list", declarations: { "background-color": "var(--site-diagram)", "padding-block": "32px" } },
  { block: "services", part: "steps", declarations: { "background-color": "var(--site-accent-soft)", gap: "20px", "padding-block": "12px" } },
  { block: "services", part: "item", declarations: { "padding-block": "24px", "padding-inline": "20px" } },
  { block: "certifications", part: "head", declarations: { "padding-top": "24px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "16px" } },
  { block: "faq", part: "item", declarations: { "padding-block": "14px" } },
  { block: "contact", part: "copy", declarations: { "background-color": "var(--site-diagram)", "padding-block": "24px" } },
];

/**
 * 工程工业 (engineering-industrial): a catalog book. White product plates with the key specs on
 * the card and the full list folded away; the accent only marks the top rule, the buttons and
 * the series labels. Colours come from the palette (registry kit); these are the other tokens.
 */
export const engineeringLook: BlockLook = {
  id: "engineering-industrial",
  templateId: "screwfast",
  fitText: "container",
  documentTitle: "工程工业首页",
  tokens: {
    "--site-container": "1200px",
    "--site-gutter": "48px",
    "--site-gutter-narrow": "32px",
    "--site-section-space": "80px",
    "--site-section-space-narrow": "52px",
    "--site-h1": "clamp(34px, 4.6vw, 58px)",
    "--site-h1-fit-min": "24px",
    "--site-h1-display": "clamp(30px, 4.8vw, 64px)",
    "--site-h2": "clamp(27px, 3vw, 38px)",
    "--site-h1-leading": "1.1",
    "--site-h1-tracking": "-0.03em",
    "--site-heading-wrap": "normal",
    "--site-heading-break": "keep-all",
    "--site-heading-max": "16em",
    "--site-heading-text-wrap": "balance",
    "--site-heading-tracking": "-0.02em",
    "--site-card-radius": "0",
    "--site-media-radius": "0",
    "--site-panel-radius": "0",
    "--site-tile-radius": "0",
    "--site-control-radius": "0",
    "--site-primary-bg": "var(--site-accent-strong)",
    "--site-primary-hover": "var(--site-ink)",
    "--site-plate-bg": "var(--site-ink)",
    "--site-plate-ink": "#fff",
    "--site-plate-muted": "rgba(255, 255, 255, 0.66)",
    "--site-plate-border": "none",
    "--site-specs-top": "3px solid var(--site-accent)",
    "--site-spec-gap": "0",
    "--site-spec-cell-bg": "transparent",
    "--site-key-bg": "transparent",
    "--site-key-gap": "0",
    "--site-key-divider": "var(--site-rule)",
    "--site-footer-bg": "var(--site-ink)",
    "--site-footer-ink": "rgba(255, 255, 255, 0.72)",
    "--site-footer-head": "#fff",
    "--site-footer-top": "none",
    "--site-eyebrow": "var(--site-muted)",
    "--site-hero-bg": "var(--site-surface)",
    "--site-frame-pad": "0",
    "--site-frame-bg": "transparent",
    "--site-frame-border": "none",
    "--site-eyebrow-bg": "transparent",
    "--site-eyebrow-pad": "0",
    "--site-head-rule": "none",
    "--site-head-pad": "0",
    "--site-value-ink": "var(--site-ink)",
    "--site-keys-border": "var(--site-rule)",
    "--site-card-edge": "none",
    "--site-badge-edge": "none",
    "--site-panel-edge": "none",
    "--site-step-top": "none",
    "--site-list-marker": "0",
    "--site-catalog-row": "minmax(0, 11em) minmax(0, 1fr)",
    "--site-spec-table-border": "var(--site-rule)",
    "--site-spec-table-head": "transparent",
    "--site-panel-bg": "var(--site-tint)",
    "--site-panel-copy-bg": "transparent",
    "--site-form-card": "var(--site-surface)",
    "--site-group-columns": "minmax(0, 12em) minmax(0, 1fr)",
    "--site-rule": "1px solid var(--site-line)",
    "--site-rule-strong": "2px solid var(--site-ink)",
  },
  layout: {
    top: ["nav"],
    main: ["hero", "products", ["industries", "capabilities"], "services", "certifications", "faq", "contact"],
    bottom: ["footer"],
  },
  defaults: {
    nav: "bar",
    hero: "split",
    products: "cards",
    industries: "list",
    capabilities: "list",
    services: "steps",
    certifications: "badges",
    faq: "accordion",
    contact: "split",
    footer: "columns",
  },
  styleDirections: {
    "spec-led": { label: "规格为主", summary: "紧凑、通底、用细线突出参数与分区。", rules: specLedRules },
    "catalog-led": { label: "目录为主", summary: "深色参数条、浅色产品带和描边卡片，适合目录询盘。", rules: catalogLedRules },
    "capability-led": { label: "工厂实力", summary: "首屏更高、能力与流程使用浅色面板带，版面更疏朗。", rules: capabilityLedRules },
  },
};
