import type { BlockLook } from "../catalog.ts";
import type { SiteStyleRule } from "../site-style.ts";

const specLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "52px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1)" } },
  { block: "products", part: "grid", declarations: { gap: "16px" } },
  { block: "industries", part: "list", declarations: { "padding-block": "18px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "18px" } },
  { block: "services", part: "steps", declarations: { gap: "1px" } },
  { block: "services", part: "item", declarations: { "padding-block": "16px" } },
  { block: "contact", part: "copy", declarations: { "padding-block": "20px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "20px" } },
  { block: "certifications", part: "list", declarations: { gap: "12px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "10px" } },
  { block: "hero", part: "actions", declarations: { "padding-block": "4px" } },
];
const catalogLedRules: SiteStyleRule[] = [
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1-display)" } },
  { block: "products", part: "grid", declarations: { gap: "24px", "padding-block": "8px" } },
  { block: "industries", part: "list", declarations: { "padding-block": "28px" } },
  { block: "capabilities", part: "list", declarations: { "padding-block": "28px" } },
  { block: "services", part: "steps", declarations: { gap: "1px", "padding-block": "8px" } },
  { block: "services", part: "item", declarations: { "padding-block": "22px" } },
  { block: "contact", part: "copy", declarations: { "padding-block": "28px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "28px" } },
  { block: "certifications", part: "list", declarations: { gap: "18px", "padding-block": "12px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "16px" } },
  { block: "hero", part: "actions", declarations: { "padding-block": "8px" } },
  { block: "products", declarations: { "background-color": "var(--site-surface)" } },
];
const capabilityLedRules: SiteStyleRule[] = [
  { block: "hero", part: "band", declarations: { "padding-block": "88px" } },
  { block: "hero", part: "title", declarations: { "font-size": "var(--site-h1-display)" } },
  { block: "products", part: "grid", declarations: { gap: "28px" } },
  { block: "industries", part: "list", declarations: { "background-color": "var(--site-accent-soft)", "padding-block": "28px" } },
  { block: "capabilities", part: "list", declarations: { "background-color": "var(--site-accent-soft)", "padding-block": "28px" } },
  { block: "services", part: "steps", declarations: { "background-color": "var(--site-accent-soft)", gap: "1px", "padding-block": "12px" } },
  { block: "services", part: "item", declarations: { "padding-block": "24px", "padding-inline": "20px" } },
  { block: "contact", part: "copy", declarations: { "background-color": "var(--site-tint)", "padding-block": "28px" } },
  { block: "contact", part: "form", declarations: { "padding-block": "28px" } },
  { block: "certifications", part: "list", declarations: { "padding-block": "16px" } },
  { block: "faq", part: "list", declarations: { "padding-block": "16px" } },
  { block: "products", part: "head", declarations: { "padding-block": "24px" } },
];

/** Grey short-path look token seams. Variants and registry wiring land in later T-057 steps. */
export const shortPathLook: BlockLook = {
  id: "technical-product",
  templateId: "tailwind-landing",
  heroTitle: "words",
  documentTitle: "灰底短路径首页",
  tokens: {
    "--site-container": "1180px",
    "--site-gutter": "48px",
    "--site-gutter-narrow": "32px",
    "--site-section-space": "64px",
    "--site-section-space-narrow": "57px",
    "--site-h1": "clamp(44px, 6vw, 78px)",
    "--site-h1-display": "clamp(44px, 6vw, 78px)",
    "--site-h2": "clamp(31px, 4vw, 52px)",
    "--site-h1-leading": "1",
    "--site-h1-tracking": "-0.065em",
    "--site-h1-narrow": "clamp(40px, 11vw, 58px)",
    "--site-heading-wrap": "anywhere",
    "--site-heading-break": "normal",
    "--site-heading-max": "16em",
    "--site-heading-text-wrap": "pretty",
    "--site-heading-tracking": "-0.05em",
    "--site-card-radius": "var(--site-radius)",
    "--site-media-radius": "24px",
    "--site-panel-radius": "24px",
    "--site-tile-radius": "9px",
    "--site-control-radius": "9px",
    "--site-primary-bg": "var(--site-accent)",
    "--site-primary-hover": "var(--site-accent-strong)",
    "--site-plate-bg": "var(--site-surface)",
    "--site-plate-ink": "var(--site-ink)",
    "--site-plate-muted": "var(--site-muted)",
    "--site-plate-border": "var(--site-line)",
    "--site-specs-top": "none",
    "--site-spec-gap": "12px",
    "--site-spec-cell-bg": "transparent",
    "--site-key-bg": "transparent",
    "--site-key-gap": "0",
    "--site-key-divider": "var(--site-rule)",
    "--site-footer-bg": "var(--site-bg)",
    "--site-footer-ink": "var(--site-muted)",
    "--site-footer-head": "var(--site-ink)",
    "--site-footer-top": "var(--site-rule)",
    "--site-eyebrow": "var(--site-accent-strong)",
    "--site-hero-bg": "var(--site-bg)",
    "--site-frame-pad": "0",
    "--site-frame-bg": "transparent",
    "--site-frame-border": "none",
    "--site-eyebrow-bg": "transparent",
    "--site-eyebrow-pad": "0",
    "--site-head-rule": "none",
    "--site-head-pad": "0",
    "--site-head-dash": "26px",
    "--site-value-ink": "var(--site-ink)",
    "--site-keys-border": "var(--site-rule)",
    "--site-card-edge": "none",
    "--site-badge-edge": "none",
    "--site-panel-edge": "none",
    "--site-step-top": "none",
    "--site-list-marker": "0",
    "--site-catalog-row": "1fr",
    "--site-catalog-columns": "repeat(2, minmax(0, 1fr))",
    "--site-product-columns": "repeat(2, minmax(0, 1fr))",
    "--site-card-pad": "20px",
    "--site-keys-columns": "1fr",
    "--site-key-display": "flex",
    "--site-step-gap": "1px",
    "--site-steps-bg": "var(--site-line)",
    "--site-step-min": "190px",
    "--site-hero-columns": "minmax(0, 1.1fr) minmax(320px, 0.9fr)",
    "--site-inquiry-bg": "var(--site-bg)",
    "--site-contact-line-size": "13px",
    "--site-submit-width": "100%",
    "--site-spec-table-border": "var(--site-rule)",
    "--site-spec-table-head": "transparent",
    "--site-panel-bg": "var(--site-surface)",
    "--site-panel-copy-bg": "transparent",
    "--site-form-card": "var(--site-surface)",
    "--site-group-columns": "1fr",
    "--site-rule": "1px solid var(--site-line)",
    "--site-rule-strong": "1px solid var(--site-line)",
  },
  layout: {
    top: ["nav"],
    main: ["hero", "products", "industries", "capabilities", "services", "contact", "certifications", "faq"],
    bottom: ["footer"],
  },
  defaults: {
    nav: "short",
    hero: "split",
    products: "cards",
    industries: "cards",
    capabilities: "cards",
    services: "cards",
    certifications: "cards",
    faq: "side",
    contact: "panel",
    footer: "line",
  },
  styleDirections: {
    "spec-led": { label: "规格为主", summary: "收紧区块间距，突出标题与参数行。", rules: specLedRules },
    "catalog-led": { label: "目录为主", summary: "放大产品目录节奏，卡片留白更舒展。", rules: catalogLedRules },
    "capability-led": { label: "工厂实力", summary: "突出能力与合作方式，使用浅色区块面。", rules: capabilityLedRules },
  },
};
