import type { BlockLook } from "../catalog.ts";

/** Grey short-path look token seams. Variants and registry wiring land in later T-057 steps. */
export const shortPathLook: BlockLook = {
  id: "technical-product",
  templateId: "tailwind-landing",
  documentTitle: "灰底短路径首页",
  tokens: {
    "--site-container": "1180px",
    "--site-gutter": "48px",
    "--site-gutter-narrow": "32px",
    "--site-section-space": "64px",
    "--site-section-space-narrow": "57px",
    "--site-h1": "clamp(44px, 6vw, 78px)",
    "--site-h1-display": "clamp(44px, 6vw, 78px)",
    "--site-h2": "clamp(31px, 4vw, 52px)",
    "--site-h1-leading": "1",
    "--site-h1-tracking": "-0.065em",
    "--site-h1-narrow": "clamp(40px, 11vw, 58px)",
    "--site-heading-wrap": "normal",
    "--site-heading-break": "keep-all",
    "--site-heading-max": "16em",
    "--site-heading-text-wrap": "balance",
    "--site-heading-tracking": "-0.05em",
    "--site-card-radius": "var(--site-radius)",
    "--site-media-radius": "24px",
    "--site-panel-radius": "24px",
    "--site-tile-radius": "9px",
    "--site-control-radius": "9px",
    "--site-primary-bg": "var(--site-accent)",
    "--site-primary-hover": "var(--site-accent-strong)",
    "--site-plate-bg": "var(--site-surface)",
    "--site-plate-ink": "var(--site-ink)",
    "--site-plate-muted": "var(--site-muted)",
    "--site-plate-border": "var(--site-line)",
    "--site-specs-top": "none",
    "--site-spec-gap": "12px",
    "--site-spec-cell-bg": "transparent",
    "--site-key-bg": "transparent",
    "--site-key-gap": "0",
    "--site-key-divider": "var(--site-rule)",
    "--site-footer-bg": "var(--site-bg)",
    "--site-footer-ink": "var(--site-muted)",
    "--site-footer-head": "var(--site-ink)",
    "--site-footer-top": "var(--site-rule)",
    "--site-eyebrow": "var(--site-accent-strong)",
    "--site-hero-bg": "var(--site-bg)",
    "--site-frame-pad": "0",
    "--site-frame-bg": "transparent",
    "--site-frame-border": "none",
    "--site-eyebrow-bg": "transparent",
    "--site-eyebrow-pad": "0",
    "--site-head-rule": "none",
    "--site-head-pad": "0",
    "--site-head-dash": "26px",
    "--site-value-ink": "var(--site-ink)",
    "--site-keys-border": "var(--site-rule)",
    "--site-card-edge": "none",
    "--site-badge-edge": "none",
    "--site-panel-edge": "none",
    "--site-step-top": "none",
    "--site-list-marker": "0",
    "--site-catalog-row": "1fr",
    "--site-catalog-columns": "repeat(2, minmax(0, 1fr))",
    "--site-product-columns": "repeat(2, minmax(0, 1fr))",
    "--site-card-pad": "20px",
    "--site-keys-columns": "1fr",
    "--site-key-display": "flex",
    "--site-step-gap": "1px",
    "--site-steps-bg": "var(--site-line)",
    "--site-step-min": "190px",
    "--site-hero-columns": "minmax(0, 1.1fr) minmax(320px, 0.9fr)",
    "--site-inquiry-bg": "var(--site-bg)",
    "--site-contact-line-size": "13px",
    "--site-submit-width": "100%",
    "--site-spec-table-border": "var(--site-rule)",
    "--site-spec-table-head": "transparent",
    "--site-panel-bg": "var(--site-surface)",
    "--site-panel-copy-bg": "transparent",
    "--site-form-card": "var(--site-surface)",
    "--site-group-columns": "1fr",
    "--site-rule": "1px solid var(--site-line)",
    "--site-rule-strong": "1px solid var(--site-line)",
  },
  layout: {
    top: ["nav"],
    main: ["hero", "products", "industries", "capabilities", "services", "contact", "certifications", "faq"],
    bottom: ["footer"],
  },
  defaults: {
    nav: "short",
    hero: "split",
    products: "cards",
    industries: "cards",
    capabilities: "cards",
    services: "cards",
    certifications: "cards",
    faq: "side",
    contact: "panel",
    footer: "line",
  },
};
