import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

export type MeasuredText = {
  slot: string;
  text: string;
  block?: string;
  top?: number;
  role?: string;
  status?: string;
  ratio?: number | null;
  checkable?: boolean;
  reason?: string;
};
export type Measurement = {
  failures: string[];
  textContrast: MeasuredText[];
  bodyLineLength: MeasuredText[];
  lineLengthExemptions: MeasuredText[];
};
export type PageReport = Measurement & { siteKey: string; width: number; english: Measurement };

const baseline = JSON.parse(readFileSync(new URL("../fixtures/t103-real-molding-measurements.json", import.meta.url), "utf8")) as {
  rows: Array<{ width: number; locales: Record<string, Record<string, number>> }>;
};
const draft = JSON.parse(readFileSync(new URL("../fixtures/t103-real-molding-draft.json", import.meta.url), "utf8")).draft;
type Target = { slot: string; text: string; role: string; reason?: string };

// This is the fixed T103 input's contract, not an inventory inferred from a report or
// generated by the production adapter. Forge declares these blocks in bright.ts;
// about/features are not rendered. Gap sentence bodies are hidden (CONTEXT.md).
function expectedTargets(locale: "zh" | "en", width: number) {
  const body: Target[] = [];
  const contrast: Target[] = [];
  const exemptions: Target[] = [];
  const localized = (value: string | Record<string, string> | null) => typeof value === "string" ? value : value?.[locale] || "";
  const supplied = (value: string) => Boolean(value) && value !== "待补充" && value !== "To be provided";
  const add = (slot: string, text: string, role: string, reason?: string) => {
    if (!supplied(text)) return;
    const target = { slot, text, role, reason };
    contrast.push(target);
    if (reason) exemptions.push(target);
    else if (role === "body") body.push(target);
  };
  const field = (slot: string, value: string | Record<string, string> | null, role = "body", reason?: string) => add(`${slot}.${locale}`, localized(value), role, reason);
  field("industry", draft.industry);
  field("hero.title", draft.content.hero.title, "heading");
  field("hero.subtitle", draft.content.hero.subtitle);
  field("hero.cta", draft.content.hero.cta, "control");
  for (const section of ["products", "industries", "services", "certifications", "faq", "contact"]) {
    field(`${section}.title`, draft.content[section].title, "heading");
    field(`${section}.${section === "contact" ? "body" : "intro"}`, draft.content[section][section === "contact" ? "body" : "intro"]);
  }
  for (const product of draft.products) {
    field(`products.${product.id}.name`, product.name, "heading");
    field(`products.${product.id}.summary`, product.summary);
    // The grouped-products declaration exposes three key specs; the full table is
    // inside closed details. Test both visible labels and values, using the input.
    for (const spec of product.specs.slice(0, 3)) {
      add(`products.${product.id}`, localized(spec.name), "body");
      add(`products.${product.id}`, localized(spec.value), "body");
    }
    add(`products.${product.id}`, locale === "zh" ? `全部参数（${product.specs.length} 项）` : `All specifications (${product.specs.length})`, "control", "按钮或控件");
  }
  for (const section of ["services", "faq", "industries", "certifications"]) {
    for (const item of draft.content[section].items) {
      field(`${section}.items.${item.id}.title`, item.title, section === "faq" ? "control" : "heading", section === "faq" ? "按钮或控件" : undefined);
      field(`${section}.items.${item.id}.body`, item.body);
      if (section === "certifications") {
        const status = locale === "en" ? ({ "已有": "Certified", "认证中": "In progress" } as Record<string, string>)[item.status] : item.status;
        add(`certifications.items.${item.id}.status`, status, "parameter", "型号或参数");
      }
    }
  }
  for (const item of draft.content.commercialTerms) field(`commercialTerms.items.${item.id}.value`, item.value);
  for (const item of draft.content.qualityProcess) {
    field(`qualityProcess.items.${item.id}.title`, item.title, "heading");
    field(`qualityProcess.items.${item.id}.body`, item.body);
  }
  for (const item of draft.content.history) {
    add(`history.items.${item.id}.year`, String(item.year), "heading");
    field(`history.items.${item.id}.event`, item.event);
  }
  for (const item of draft.content.equipment) {
    field(`equipment.items.${item.id}.name`, item.name, "heading");
    field(`equipment.items.${item.id}.spec`, item.spec, "parameter", "型号或参数");
    if (item.quantity !== null) add(`equipment.items.${item.id}.quantity`, locale === "zh" ? `数量：${item.quantity} 台` : `${item.quantity} units`, "parameter", "型号或参数");
  }
  field("contact.email", draft.content.contact.email, "parameter", "邮箱或电话");
  field("companyName", draft.companyName, "control");
  // Visible shell controls have data-sitecraft-ui rather than authored slots.
  // Their labels and responsive visibility are declared by nav/contact fragments.
  for (const text of ["中", "EN", locale === "zh" ? "发送询盘" : "Send inquiry"]) add("", text, "control", "按钮或控件");
  // The mobile/tablet nav is closed; its links have no visible measurement.
  if (width === 1440) {
    for (const section of ["products", "services"]) field(`navigation.${section}`, draft.navigation[section], "navigation", "导航");
    for (const text of locale === "zh" ? ["应用行业", "认证状态", "常见问题"] : ["Industries", "Certifications", "Questions"]) add("", text, "navigation", "导航");
  } else add("", locale === "zh" ? "菜单" : "Menu", "control", "按钮或控件");
  return { body, contrast, exemptions };
}

// Wrapping trims whitespace at line boundaries; the renderer also inserts these
// two break controls in parameters/email. Keep punctuation, case, numbers and units.
const textKey = (text: string) => text.replace(/[\s\u200b\u2060]/g, "");

export function assertT103MeasurementCoverage(measured: Measurement, width: number, locale: "zh" | "en") {
  const expected = baseline.rows.find((entry) => entry.width === width)!;
  for (const field of ["textContrast", "lineLengthExemptions"] as const) {
    assert.ok(Array.isArray(measured[field]) && measured[field].length >= expected.locales[locale][field], `${width} ${locale} ${field}: measurements must not be fewer than the known-bad baseline`);
  }
  assert.ok(Array.isArray(measured.bodyLineLength), `${width} ${locale} bodyLineLength: measurements must be present`);
  const targets = expectedTargets(locale, width);
  // Key specs are non-paragraph dl text. Only declared sentence slots require
  // line measurements; matching a product root cannot substitute for its summary.
  for (const target of targets.body.filter((target) => target.slot.endsWith(`.${locale}`))) {
    const lines = measured.bodyLineLength.filter((entry) => entry.slot === target.slot);
    const message = `${width} ${locale} bodyLineLength ${target.slot}: complete input paragraph must be measured`;
    assert.ok(lines.length && lines.every((entry) => Number.isFinite(entry.top)), message);
    assert.equal(textKey([...lines].sort((a, b) => a.top! - b.top!).map((entry) => entry.text).join("")), textKey(target.text), message);
  }
  for (const target of targets.contrast) {
    const entries = measured.textContrast.filter((entry) => entry.slot === target.slot && entry.role === target.role);
    const message = `${width} ${locale} textContrast ${target.slot}: input text must have a measured contrast entry`;
    // The scanner reports at most 160 characters per text node. Full sentence
    // coverage is proved above by uncapped line text, not by these snippets.
    const expectedText = textKey(target.text.slice(0, 160));
    if (!target.slot || (target.slot.startsWith("products.") && !target.slot.endsWith(`.${locale}`))) {
      assert.ok(entries.some((entry) => textKey(entry.text) === expectedText && entry.status === "measured" && typeof entry.ratio === "number" && Number.isFinite(entry.ratio) && (target.role !== "body" || entry.checkable === true)), message);
    } else if (target.slot === `contact.email.${locale}`) {
      // Contact panel and footer each declare the input email.
      assert.equal(entries.length, 2, message);
      assert.ok(entries.every((entry) => textKey(entry.text) === expectedText && entry.status === "measured" && typeof entry.ratio === "number" && Number.isFinite(entry.ratio)), message);
    } else {
      assert.equal(textKey(entries.map((entry) => entry.text).join("")), expectedText, message);
      assert.ok(entries.every((entry) => entry.status === "measured" && typeof entry.ratio === "number" && Number.isFinite(entry.ratio) && (!(target.role === "body" || target.role === "heading") || entry.checkable === true)), message);
    }
  }
  for (const target of targets.exemptions) {
    const entries = measured.lineLengthExemptions.filter((entry) => entry.slot === target.slot && textKey(entry.text) === textKey(target.text) && entry.reason === target.reason);
    assert.equal(entries.length, target.slot === `contact.email.${locale}` ? 2 : 1, `${width} ${locale} lineLengthExemptions ${target.slot}: input text and declared exemption must be measured`);
  }
}
